# Numpy Assignment 1

In [1]:
#importing numpy
import numpy as np

### Null vector of size 10 but fifth value is 1

In [2]:
nul_vctr = np.zeros(10)

In [3]:
nul_vctr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
nul_vctr[4] = 1

In [5]:
nul_vctr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Create a vector with values ranging from 10 to 49 

In [6]:
vctr = np.arange(10,50)

In [7]:
vctr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Find indices of non-zero elements from [1,2,0,0,4,0] 

In [9]:
l = np.array([1,2,0,0,4,0])

In [10]:
np.where(l>0)

(array([0, 1, 4], dtype=int64),)

### Create a 10x10 array with random values and find the minimum and maximum values. 

In [11]:
arr = np.random.rand(10,10)

In [12]:
arr

array([[0.82254844, 0.65130944, 0.57971433, 0.72817915, 0.1540887 ,
        0.95020681, 0.0846507 , 0.38266411, 0.33109021, 0.45912776],
       [0.02506663, 0.87644462, 0.84315024, 0.03455052, 0.11665316,
        0.57424816, 0.56128154, 0.10181018, 0.01056676, 0.85930874],
       [0.29664894, 0.00125548, 0.23200479, 0.20720051, 0.9534913 ,
        0.973031  , 0.44333422, 0.95786869, 0.58368109, 0.46236273],
       [0.21791185, 0.55465979, 0.01184206, 0.54362857, 0.19617137,
        0.08239545, 0.24568228, 0.86118959, 0.26117433, 0.08324916],
       [0.06702684, 0.50849957, 0.44650998, 0.32513718, 0.85702617,
        0.36876123, 0.47547505, 0.66216155, 0.64606697, 0.01736001],
       [0.84777339, 0.35145976, 0.36944739, 0.32628024, 0.01579271,
        0.34433631, 0.27211651, 0.46702127, 0.96816855, 0.8117038 ],
       [0.38034747, 0.49656601, 0.19439912, 0.43281888, 0.05783008,
        0.90679595, 0.69624504, 0.60596713, 0.44918305, 0.66849919],
       [0.65544004, 0.90183558, 0.3019697

In [13]:
arr.shape

(10, 10)

In [14]:
arr.max()

0.9873728921667001

In [15]:
arr.min()

0.0012554828170671106

### Create a random vector of size 30 and find the mean value. 

In [16]:
arr = np.random.rand(30)

In [17]:
arr

array([0.73088904, 0.61075125, 0.14972328, 0.07182206, 0.41975189,
       0.76179305, 0.72557623, 0.29202907, 0.37273222, 0.79872924,
       0.93733564, 0.30655839, 0.16967766, 0.6508757 , 0.27368806,
       0.17917689, 0.91554103, 0.21581771, 0.74328016, 0.63951911,
       0.9959458 , 0.47506691, 0.32125501, 0.52178411, 0.51191767,
       0.10505461, 0.30638552, 0.68621472, 0.69562473, 0.06984733])

In [18]:
arr.mean()

0.48847880328336934